"""Minimal PN532 passive-tag emulator firmware.

Puts the PN532 into ISO14443-A target (card emulation) mode so an external
reader -- e.g. the ../tmp-just-read board -- detects it as a passive NFC tag
and reads the UID below. No WiFi, buzzer, LED or MQTT.

Wiring matches the Prismo pin map (see firmware/src/config.py):
    SCK  -> GPIO 1
    MISO -> GPIO 2
    MOSI -> GPIO 3
    SS   -> GPIO 4

Note: the PN532 can emulate the tag's anticollision + UID, but NOT a full
MiFare Classic with authenticated sectors. A reader will see a 4-byte UID:
0x08 followed by the 3 bytes generated by the emulator.
"""
import time
import os
import sys
import _thread
from machine import SPI, Pin
from PN532 import PN532

# --- Pin / bus config (from firmware/src/config.py) -------------------------
NFC_BAUDRATE = 1_000_000
PIN_NFC_SCK = 1
PIN_NFC_MISO = 2
PIN_NFC_MOSI = 3
PIN_NFC_SS = 4

def main():
    print("Device State: INIT")
    print("Starting PN532 passive-tag emulator")

    spi = SPI(1, baudrate=NFC_BAUDRATE, polarity=0, phase=0,
              sck=Pin(PIN_NFC_SCK),
              mosi=Pin(PIN_NFC_MOSI),
              miso=Pin(PIN_NFC_MISO))

    cs_pin = Pin(PIN_NFC_SS, Pin.OUT)
    cs_pin.on()

    # Init PN532, retrying until it answers.
    while True:
        try:
            nfc = PN532(spi, cs_pin, debug=False)
            ic, ver, rev, support = nfc.get_firmware_version()
            print("PN532 found, firmware {}.{}".format(ver, rev))
            nfc.SAM_configuration()
            break
        except Exception as e:
            print("PN532 init failed, retrying:", e)
            time.sleep(1)

    # Global variable to pass the read line from the thread
    global serial_cmd
    serial_cmd = None

    def serial_reader():
        global serial_cmd
        input_buffer = ""
        while True:
            try:
                char = sys.stdin.read(1)
                if char:
                    if char in ('\n', '\r'):
                        line = input_buffer.strip()
                        input_buffer = ""
                        if line:
                            serial_cmd = line
                    else:
                        input_buffer += char
            except Exception:
                time.sleep(0.1)

    # Start the background thread for serial input
    _thread.start_new_thread(serial_reader, ())

    # Wait for user input
    while True:
        print("\nDevice State: WAITING_FOR_SERIAL")
        print("Emulation stopped. Waiting for a new hex key via serial terminal.")
        print("Please enter a 6-character hex string (e.g. '123456'):")
        
        while not serial_cmd:
            time.sleep(0.1)
            
        line = serial_cmd
        serial_cmd = None
        
        try:
            if line.lower() == 'stop':
                continue # Already stopped, just loop back
                
            # Check for duration e.g. "aabbcc:5"
            duration_s = None
            if ":" in line:
                parts = line.split(":")
                line = parts[0]
                try:
                    duration_s = int(parts[1])
                except ValueError:
                    pass
                    
            new_uid = bytes.fromhex(line)
            if len(new_uid) == 3:
                uid = new_uid
                uid_str = "".join("{:02x}".format(b) for b in uid)
                print("\nDevice State: EMULATING_CUSTOM")
                if duration_s:
                    print("Now emulating NFCID1:", uid_str, "for", duration_s, "seconds")
                else:
                    print("Now emulating NFCID1:", uid_str)
                
                # Emulate this custom key until a new serial command arrives or timer expires
                start_time = time.ticks_ms()
                while not serial_cmd:
                    if duration_s is not None and time.ticks_diff(time.ticks_ms(), start_time) >= duration_s * 1000:
                        print(f"Time limit of {duration_s}s reached. Stopping emulation.")
                        break

                    activated = nfc.tg_init_as_target(uid, timeout=500)
                    if activated is not None:
                        print("Activated by external reader")
                        time.sleep(0.5)
                        
                if serial_cmd and serial_cmd.lower() == 'stop':
                    serial_cmd = None
            else:
                print("Error: UID must be exactly 3 bytes (6 hex chars).")
        except ValueError:
            print("Error: Invalid input. Enter 6 hex chars (e.g. '123456') or 'stop'.")


main()
