version: '3.8'

services:
  backend:
    image: ghcr.io/${IMAGE_NAME}-backend:${COMMIT_SHA}
    deploy:
      update_config:
        order: start-first
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - COMMIT_SHA=${COMMIT_SHA}
      - SESSION_SECRET=${SESSION_SECRET}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - MQTT_URL=${MQTT_URL}
      - PORT=4000
    networks:
      - infra_reverse-proxy
      - infra_postgres-net
      - infra_mqtt-net
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4000/api/health']
      interval: 15s
      timeout: 30s
      retries: 4
      start_period: 60s

  client:
    image: ghcr.io/${IMAGE_NAME}-client:${COMMIT_SHA}
    deploy:
      update_config:
        order: start-first
    networks:
      - infra_reverse-proxy

networks:
  infra_reverse-proxy:
    external: true
  infra_postgres-net:
    external: true
  infra_mqtt-net:
    external: true
