M48
; DRILL file {KiCad 9.0.6} date 2026-04-06T12:22:07+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-06T12:22:07+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X122.165Y-90.35
X122.165Y-92.85
X150.255Y-58.46
X152.755Y-58.46
T2
X114.6Y-80.5
X139.8Y-52.7
M30
