import type { UUID, EntityName } from '@prismo/shared/entities';
import { isEntityName } from '@prismo/shared/entities';
import { pool } from '@/db/pg';
import { mutate } from '@/db/mutate';
import { EntityError } from './entity-error';
import type { TypedEntityRow } from '@/db/entities';
import { insertEntity, softDelete } from '@/db/entities';

export async function deleteEntity(workspaceId: UUID, id: UUID): Promise<{ id: UUID; type: EntityName }> {
  const { rows: [entity] } = await pool.query<TypedEntityRow>(
    `SELECT id, type, data FROM entities
     WHERE id = $1 AND workspace_id = $2 AND deleted = false`,
    [id, workspaceId],
  );
  if (!entity) {
    throw new EntityError(404, 'Entity not found');
  }

  await mutate(workspaceId, async (client, seq) => {
    const deletedId = await softDelete(client, seq, workspaceId, id);
    if (!deletedId) throw new EntityError(404, 'Entity not found');
  });

  return { id, type: entity.type };
}

function isJsonValue(value: unknown): boolean {
  if (value === null) return true;
  if (Array.isArray(value)) return value.every(isJsonValue);
  const t = typeof value;
  if (t === 'string' || t === 'number' || t === 'boolean') return true;
  if (t === 'object') return Object.values(value as object).every(isJsonValue);
  return false;
}

function toFlatData(data: unknown): Record<string, unknown> {
  if (typeof data !== 'object' || data === null || Array.isArray(data)) {
    throw new EntityError(400, 'data must be an object');
  }
  for (const [field, value] of Object.entries(data)) {
    if (!isJsonValue(value)) {
      throw new EntityError(400, `Field "${field}" must be a JSON-serializable value`);
    }
  }
  return data as Record<string, unknown>;
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export async function createEntity(
  workspaceId: UUID,
  type: unknown,
  data: unknown,
): Promise<{ id: UUID; type: EntityName }> {
  if (!isEntityName(type)) {
    throw new EntityError(400, `Unsupported entity type "${String(type)}"`);
  }

  const { id, ...rest } = toFlatData(data);
  if (typeof id !== 'string' || !UUID_RE.test(id)) {
    throw new EntityError(400, '"id" must be a UUID generated by the client');
  }

  const row = await mutate(workspaceId, (client, seq) =>
    insertEntity(client, workspaceId, type, rest, seq, id),
  );
  if (!row) {
    throw new EntityError(409, `Entity "${id}" belongs to a different workspace/type, or was deleted`);
  }
  return { id: row.id, type };
}
