/**
 * Per-run firmware provisioning for the connected ESP32-C3.
 *
 * The device's WiFi + MQTT credentials change every run (the MQTT token is
 * generated by the web app), so the firmware must be configured per run.
 *
 * We use the documented local-dev override mechanism (firmware/README.md →
 * "Local Dev Credentials"): the frozen src/config.py does
 * `from src.config_dev import *`, so dropping a src/config_dev.py onto the
 * device filesystem and soft-resetting overrides the baked-in values — no
 * ESP-IDF rebuild and no physical power-cycle. The base firmware (MicroPython +
 * frozen Prismo app) must already be flashed once during stand setup.
 */
import { mkdtemp, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { config } from './env';
import { run } from './exec';

export interface DeviceProvision {
	wifiSsid: string;
	wifiPass: string;
	mqttHost: string;
	mqttPort: string;
	mqttUser: string;
	mqttPass: string;
	mode: string;
}

/** MicroPython literal — single-quote and escape so creds with symbols are safe. */
function pyStr(value: string): string {
	return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function configDevSource(p: DeviceProvision): string {
	return (
		[
			'# Generated by the test-stand e2e run — overrides baked-in config.',
			`WIFI_SSID = ${pyStr(p.wifiSsid)}`,
			`WIFI_PASS = ${pyStr(p.wifiPass)}`,
			`MQTT_URL  = ${pyStr(`mqtt://${p.mqttHost}:${p.mqttPort}`)}`,
			`MQTT_USER = ${pyStr(p.mqttUser)}`,
			`MQTT_PASS = ${pyStr(p.mqttPass)}`,
			`DEVICE_MODE = ${pyStr(p.mode)}`,
			// Skip boot animation/sounds — the animation trips the boot WDT, and a
			// silent board is preferable on an automated stand.
			`QUICK_START = ${config.quickStart ? 'True' : 'False'}`,
			`MUTE_BUZZER = ${config.muteBuzzer ? 'True' : 'False'}`
		].join('\n') + '\n'
	);
}

function mpremoteBaseArgs(): string[] {
	return ['connect', config.serialPort];
}

/**
 * Optional: erase + write the base firmware binary with esptool.
 *
 * NOTE: the ESP32-C3 USB-JTAG does not auto-boot after a write — it needs a
 * manual power-cycle (see firmware/flash.sh). Off by default; only useful for
 * the one-time stand setup, not for unattended per-run flashing.
 */
export async function flashBaseFirmware(): Promise<void> {
	if (!config.firmwareBin) {
		throw new Error('TESTSTAND_FIRMWARE_BIN must point to firmware.bin to flash the base image');
	}
	await run(config.esptoolBin, ['--chip', 'esp32c3', '--port', config.serialPort, 'erase-flash']);
	await run(config.esptoolBin, [
		'--chip',
		'esp32c3',
		'--port',
		config.serialPort,
		'--baud',
		'460800',
		'write-flash',
		'0x0',
		config.firmwareBin
	]);
	console.warn(
		'⚠️  Base firmware written. Power-cycle the ESP32-C3 (unplug 2s, replug) before continuing.'
	);
}

/**
 * Inject the per-run WiFi/MQTT config onto the device and soft-reset it.
 * After this returns, the device reboots, joins the hotspot, connects to MQTT
 * and starts publishing status heartbeats (every 5s).
 */
export async function provisionDevice(p: DeviceProvision): Promise<void> {
	const dir = await mkdtemp(path.join(tmpdir(), 'prismo-stand-'));
	const file = path.join(dir, 'config_dev.py');
	try {
		await writeFile(file, configDevSource(p), 'utf8');

		// Ensure the :src directory exists on the device FS (ignore "already exists").
		await run(config.mpremoteBin, [...mpremoteBaseArgs(), 'fs', 'mkdir', ':src'], {
			check: false
		});
		// Copy the override and soft-reset so main.py re-runs with new config.
		await run(config.mpremoteBin, [...mpremoteBaseArgs(), 'fs', 'cp', file, ':src/config_dev.py']);
		await run(config.mpremoteBin, [...mpremoteBaseArgs(), 'reset']);
	} finally {
		await rm(dir, { recursive: true, force: true });
	}
}
