DEBUG=False
QUICK_START=True

# DEVICE_MODE = 'ACCESS' 
DEVICE_MODE = 'MACHINE'

SUCCESS_SIGNAL_DURATION = 2000 
ERROR_SIGNAL_DURATION = 1000 

PWM_FREQ = 1000
NFC_BAUDRATE = 1000000

PIN_RGB_RED = 0
PIN_RGB_GREEN = 1
PIN_RGB_BLUE = 2

PIN_NFC_RESET = 3
PIN_NFC_SCK = 4
PIN_NFC_MISO = 5
PIN_NFC_MOSI = 6

PIN_NFC_SS = 7

PIN_OUTPUT_ERROR = 8
PIN_OUTPUT_SUCESS = 9

PIN_BUZZER = 10
PIN_RELAY = 21