name: Build MicroPython Firmware

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nu31hackerspace/prismo-web-flasher
  HOST: ${{ vars.HOST }}
  SSH_KEY: ${{ secrets.ROOT_SSH_PRIVATE_KEY }}
  COMMIT_SHA: ${{ github.sha }}
  DEPLOY_USER: ${{ vars.USERNAME }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y git wget flex bison gperf python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0

      - name: Build Firmware
        working-directory: firmware
        run: bash build.sh

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: prismo-firmware.bin
          path: firmware/dist/firmware.bin

      - name: Prepare Web Flasher
        run: |
          mkdir -p web-flasher/bin
          cp firmware/dist/firmware.bin web-flasher/bin/firmware.bin

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: web-flasher
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            GIT_COMMIT_SHA=${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file for Docker Stack
        run: |
          echo "IMAGE_NAME='${{ env.IMAGE_NAME }}'" >> .env
          echo "COMMIT_SHA='${{ env.COMMIT_SHA }}'" >> .env

      - name: Setup docker remote context
        uses: cssnr/stack-deploy-action@v1
        with:
          name: prismo-web-flasher
          file: web-flasher/docker-stack.yml
          host: ${{ env.HOST}}
          port: 22
          user: ${{ env.DEPLOY_USER }}
          ssh_key: ${{ env.SSH_KEY }}
          env_file: .env
          detach: false
          prune: true
          resolve_image: 'always'
          summary: true
