name: Web merge requset pipeline

on:
  pull_request:

jobs:
  backend-lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm install --workspace=backend

      - name: Lint
        run: npm run lint --workspace=backend

  client-lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm install --workspace=client

      - name: Lint
        run: npm run lint --workspace=client
