version: '3.8'

services:
  app:
    image: ghcr.io/${IMAGE_NAME}:${COMMIT_SHA}
    deploy:
      update_config:
        order: start-first
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - ORIGIN=${ORIGIN}
      - COMMIT_SHA=${COMMIT_SHA}
      - SESSION_SECRET=${SESSION_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - MQTT_URL=${MQTT_URL}
    networks:
      - infra_reverse-proxy
      - infra_mongo-rs-net
      - infra_mqtt-net
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 15s
      timeout: 30s
      retries: 4
      start_period: 60s

  worker:
    image: ghcr.io/nu31hackerspace/prismo-worker:${COMMIT_SHA}
    deploy:
      replicas: 1
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - MQTT_URL=${MQTT_URL}
    networks:
      - infra_mongo-rs-net
      - infra_mqtt-net

networks:
  infra_reverse-proxy:
    external: true
  infra_mongo-rs-net:
    external: true
  infra_mqtt-net:
    external: true
