services:
  mongo:
    image: mongo:8
    ports:
      - '27017:27017'
    command: --replSet rs0
    healthcheck:
      test: mongosh --eval "db.runCommand({ping:1})" --quiet
      interval: 3s
      timeout: 3s
      retries: 10

  mongo-init:
    image: mongo:8
    depends_on:
      mongo:
        condition: service_healthy
    restart: 'no'
    entrypoint: >
      mongosh --host mongo --eval
      "try { rs.status() } catch(e) { rs.initiate({_id:'rs0', members:[{_id:0, host:'mongo:27017'}]}) }"

  mqtt:
    build: ./mosquitto
    ports:
      - '1883:1883'
    environment:
      - MQTT_ADMIN_USER=admin
      - MQTT_ADMIN_PASSWORD=admin
    healthcheck:
      test: mosquitto_sub -h localhost -p 1883 -u admin -P admin -t '$$SYS/#' -C 1 -W 2
      interval: 3s
      timeout: 5s
      retries: 10

  worker:
    build:
      context: ..
      dockerfile: web/worker/Dockerfile
    depends_on:
      mongo:
        condition: service_healthy
      mongo-init:
        condition: service_completed_successfully
    environment:
      - MONGODB_URL=mongodb://mongo:27017/prismo?directConnection=true&replicaSet=rs0
      - MQTT_URL=mqtt://mqtt:1883
    restart: on-failure
