import http from 'node:http';
import process from 'node:process';
// @ts-ignore - generated by `npm run build`
import { handler } from './build/handler.js';

const host = process.env.HOST ?? '0.0.0.0';
const port = Number(process.env.PORT ?? 3000);

const httpServer = http.createServer(handler);

httpServer.listen({ host, port }, () => {
	console.log(`Listening on http://${host}:${port}`);
});

process.on('SIGTERM', () => httpServer.close());
process.on('SIGINT', () => httpServer.close());
